name: fitness_mobile
description: "Clean, production-grade fitness tracking app."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  

  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
